In [1]:
import pandas as pd
import geopandas as gpd
import re

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
month = "July"

In [3]:
RentalList = pd.read_excel("BLM Rents July 2020.xlsx", header = 4, usecols = 8, sheet_name="MPLP")

/anaconda3/lib/python3.6/site-packages/pandas/io/excel.py:527: FutureWarning: Passing in an integer for `usecols` has been deprecated. Please pass in a list of int from 0 to `usecols` inclusive instead.
  usecols = _maybe_convert_usecols(usecols)

In [4]:
RentalList

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments
0,MTM101460,DAWSON,MONTANA,2021-07-01,1193.80,2388.0,NaN,NaN,NaN
1,MTM101461,DAWSON,MONTANA,2021-07-01,920.00,1840.0,NaN,NaN,NaN
2,MTM101462,DAWSON,MONTANA,2021-07-01,864.95,1730.0,NaN,NaN,NaN
3,MTM101463,DAWSON,MONTANA,2021-07-01,803.90,1608.0,NaN,NaN,NaN
4,MTM101464,DAWSON,MONTANA,2021-07-01,320.00,640.0,NaN,NaN,NaN
5,MTM101465,DAWSON,MONTANA,2021-07-01,318.07,638.0,NaN,NaN,NaN
6,MTM101471,DAWSON,MONTANA,2021-07-01,1600.00,3200.0,12044.0,NaN,NaN
7,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
8,MTM109323,FALLON,MONTANA,2027-07-01,160.00,240.0,NaN,NaN,Keep: 7 years remaining
9,MTM109324,FALLON,MONTANA,2027-07-01,120.00,180.0,NaN,NaN,Keep: 7 years remaining
10,MTM109325,FALLON,MONTANA,2027-07-01,160.00,240.0,NaN,NaN,Keep: 7 years remaining
11,MTM109326,FALLON,MONTANA,2027-07-01,280.00,420.0,NaN,NaN,Keep: 7 years remaining
12,MTM109327,FALLON,MONTANA,2027-07-01,40.00,60.0,NaN,NaN,Keep: 7 years remaining
13,MTM109328,FALLON,MONTANA,2027-07-01,200.00,300.0,1440.0,NaN,Keep: 7 years remaining
14,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
15,MTM109204,GARFIELD,MONTANA,2027-07-01,360.00,540.0,NaN,NaN,NaN
16,MTM109205,GARFIELD,MONTANA,2027-07-01,240.00,360.0,NaN,NaN,NaN
17,MTM109206,GARFIELD,MONTANA,2027-07-01,600.00,900.0,NaN,NaN,NaN
18,MTM109207,GARFIELD,MONTANA,2027-07-01,120.00,180.0,1980.0,NaN,NaN
19,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
20,MTM101475,POWDER RIVER,MONTANA,2021-07-01,960.00,1920.0,NaN,NaN,NaN
21,MTM101477,POWDER RIVER,MONTANA,2021-07-01,1049.60,2100.0,NaN,NaN,NaN
22,MTM109357,POWDER RIVER,MONTANA,2021-07-01,280.33,421.5,NaN,NaN,NaN
23,MTM109359,POWDER RIVER,MONTANA,2021-07-01,600.00,900.0,5341.5,NaN,NaN
24,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
25,MTM101455,RICHLAND,MONTANA,2021-07-01,10.32,22.0,NaN,NaN,NaN
26,MTM101456,RICHLAND,MONTANA,2021-07-01,5.88,12.0,NaN,NaN,NaN
27,MTM101458,RICHLAND,MONTANA,2021-07-01,40.00,80.0,NaN,NaN,NaN
28,MTM101466,RICHLAND,MONTANA,2021-07-01,245.38,492.0,606.0,NaN,NaN
29,NaN,NaN,NaN,NaT,NaN,21411.5,21411.5,NaN,NaN

In [5]:
#dropping blank rows from dataframe using "all"
RentalList.dropna(how = 'all', inplace = True)

In [6]:
RentalList

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments
0,MTM101460,DAWSON,MONTANA,2021-07-01,1193.80,2388.0,NaN,NaN,NaN
1,MTM101461,DAWSON,MONTANA,2021-07-01,920.00,1840.0,NaN,NaN,NaN
2,MTM101462,DAWSON,MONTANA,2021-07-01,864.95,1730.0,NaN,NaN,NaN
3,MTM101463,DAWSON,MONTANA,2021-07-01,803.90,1608.0,NaN,NaN,NaN
4,MTM101464,DAWSON,MONTANA,2021-07-01,320.00,640.0,NaN,NaN,NaN
5,MTM101465,DAWSON,MONTANA,2021-07-01,318.07,638.0,NaN,NaN,NaN
6,MTM101471,DAWSON,MONTANA,2021-07-01,1600.00,3200.0,12044.0,NaN,NaN
8,MTM109323,FALLON,MONTANA,2027-07-01,160.00,240.0,NaN,NaN,Keep: 7 years remaining
9,MTM109324,FALLON,MONTANA,2027-07-01,120.00,180.0,NaN,NaN,Keep: 7 years remaining
10,MTM109325,FALLON,MONTANA,2027-07-01,160.00,240.0,NaN,NaN,Keep: 7 years remaining
11,MTM109326,FALLON,MONTANA,2027-07-01,280.00,420.0,NaN,NaN,Keep: 7 years remaining
12,MTM109327,FALLON,MONTANA,2027-07-01,40.00,60.0,NaN,NaN,Keep: 7 years remaining
13,MTM109328,FALLON,MONTANA,2027-07-01,200.00,300.0,1440.0,NaN,Keep: 7 years remaining
15,MTM109204,GARFIELD,MONTANA,2027-07-01,360.00,540.0,NaN,NaN,NaN
16,MTM109205,GARFIELD,MONTANA,2027-07-01,240.00,360.0,NaN,NaN,NaN
17,MTM109206,GARFIELD,MONTANA,2027-07-01,600.00,900.0,NaN,NaN,NaN
18,MTM109207,GARFIELD,MONTANA,2027-07-01,120.00,180.0,1980.0,NaN,NaN
20,MTM101475,POWDER RIVER,MONTANA,2021-07-01,960.00,1920.0,NaN,NaN,NaN
21,MTM101477,POWDER RIVER,MONTANA,2021-07-01,1049.60,2100.0,NaN,NaN,NaN
22,MTM109357,POWDER RIVER,MONTANA,2021-07-01,280.33,421.5,NaN,NaN,NaN
23,MTM109359,POWDER RIVER,MONTANA,2021-07-01,600.00,900.0,5341.5,NaN,NaN
25,MTM101455,RICHLAND,MONTANA,2021-07-01,10.32,22.0,NaN,NaN,NaN
26,MTM101456,RICHLAND,MONTANA,2021-07-01,5.88,12.0,NaN,NaN,NaN
27,MTM101458,RICHLAND,MONTANA,2021-07-01,40.00,80.0,NaN,NaN,NaN
28,MTM101466,RICHLAND,MONTANA,2021-07-01,245.38,492.0,606.0,NaN,NaN
29,NaN,NaN,NaN,NaT,NaN,21411.5,21411.5,NaN,NaN

In [7]:
SerialNumbers = RentalList.loc[:,"LEASE NO."]

In [8]:
SerialNumbers.dropna(inplace = True)

In [9]:
SerialNumbers

0     MTM101460
1     MTM101461
2     MTM101462
3     MTM101463
4     MTM101464
5     MTM101465
6     MTM101471
8     MTM109323
9     MTM109324
10    MTM109325
11    MTM109326
12    MTM109327
13    MTM109328
15    MTM109204
16    MTM109205
17    MTM109206
18    MTM109207
20    MTM101475
21    MTM101477
22    MTM109357
23    MTM109359
25    MTM101455
26    MTM101456
27    MTM101458
28    MTM101466
Name: LEASE NO., dtype: object

In [10]:
shapefile = gpd.read_file("zip://Master Shapefile 4-2-20.zip")

In [11]:
shapefile.columns

Index(['OBJECTID_1', 'OBJECTID_2', 'OBJECTID', 'LEASE_NO', 'EFFECTIVE',
       'EXPIRATION', 'TOTAL_PAID', 'ACRES', 'COUNTY', 'ST', 'Ownership',
       'Shape_Leng', 'GeneralLoc', 'Due_Year', 'DUE_DATE', 'NO__OF_ACR',
       'HYPERLINK', 'Comments', 'Shape_Le_1', 'Shape_Le_2', 'Shape_Area',
       'geometry'],
      dtype='object')

In [12]:
shapefile["LEASE_NO"]

0            NDM101156
1            NDM101159
2            NDM101160
3            NDM101164
4            NDM101166
5            NDM101169
6            NDM101172
7            NDM101173
8            NDM101180
9            MTM101455
10           MTM101456
11           MTM101458
12           MTM101464
13           MTM101465
14           MTM101475
15           MTM101477
16           NDM101479
17           NDM102132
18           NDM102136
19           NDM102130
20           SDM102222
21           SDM102219
22           SDM102226
23           SDM102664
24           SDM103746
25           SDM103748
26           SDM103750
27           SDM103751
28           SDM103758
29           SDM103761
             ...
1439        NMNM139876
1440        NMNM139877
1441        NMNM139878
1442        NMNM139879
1443        NMNM140301
1444        NMNM140302
1445        KSNM140298
1446    WY2020-03-6024
1447    WY2020-03-6183
1448    WY2020-03-6229
1449    WY2020-03-6230
1450    WY2020-03-6231
1451    WY2020-03-6264
1452    WY2020-03-6317
1453    WY2020-03-6321
1454    WY2020-03-6324
1455    WY2020-03-6331
1456    WY2020-03-6333
1457    WY2020-03-6335
1458    WY2020-03-6342
1459    WY2020-03-6358
1460    WY2020-03-6398
1461    WY2020-03-6399
1462    WY2020-03-6400
1463    WY2020-03-6401
1464    WY2020-03-6402
1465    WY2020-03-6403
1466    WY2020-03-6655
1467    WY2020-03-6601
1468    WY2020-03-6607
Name: LEASE_NO, Length: 1469, dtype: object

In [13]:
RentalShapeFile = shapefile.loc[shapefile["LEASE_NO"].isin(SerialNumbers)]

In [14]:
RentalShapeFile["LEASE_NO"].count()
SerialNumbers.count()

25

25

In [15]:
#mismatching - most likely due to mismatching serial number text

In [16]:
testSerial = SerialNumbers.loc[146]

KeyError: 146

In [17]:
testSerial
re.findall('[\w]+', testSerial)[0]

NameError: name 'testSerial' is not defined

In [18]:
#creating function to run on a pandas series to clean up mistakenly placed special chars at end of serial number on rental spreadsheet
def replaceSpecialChars(serial):
    cleanedSerial = re.findall('[\w]+', serial)[0]
    return cleanedSerial

In [19]:
CleanedSerials = SerialNumbers.apply(lambda x: replaceSpecialChars(x))

In [20]:
RentalShapeFile = shapefile.loc[shapefile["LEASE_NO"].isin(CleanedSerials)]

In [21]:
RentalShapeFile["LEASE_NO"].count()
SerialNumbers.count()

25

25

In [22]:
RentalShapeFile.to_file(month + " 2020 - Rental Tracts.shp")

In [23]:
states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

In [24]:
#inversing dictionary
statetoInits = {v: k for k, v in states.items()}

In [25]:
RentalList.info()
RentalList["STATE"] = RentalList["STATE"].astype(str)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26 entries, 0 to 29
Data columns (total 9 columns):
LEASE NO.           25 non-null object
COUNTY              25 non-null object
STATE               25 non-null object
EXPIRATION          25 non-null datetime64[ns]
ACRES               25 non-null float64
RENTAL              26 non-null float64
COUNTY.1            6 non-null float64
Y/N                 0 non-null float64
Mishaun Comments    6 non-null object
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 2.0+ KB

In [26]:
RentalList["St. Initials"] = RentalList["STATE"].apply(lambda x: x.title()).map(statetoInits)

In [27]:
RentalList

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments,St. Initials
0,MTM101460,DAWSON,MONTANA,2021-07-01,1193.80,2388.0,NaN,NaN,NaN,MT
1,MTM101461,DAWSON,MONTANA,2021-07-01,920.00,1840.0,NaN,NaN,NaN,MT
2,MTM101462,DAWSON,MONTANA,2021-07-01,864.95,1730.0,NaN,NaN,NaN,MT
3,MTM101463,DAWSON,MONTANA,2021-07-01,803.90,1608.0,NaN,NaN,NaN,MT
4,MTM101464,DAWSON,MONTANA,2021-07-01,320.00,640.0,NaN,NaN,NaN,MT
5,MTM101465,DAWSON,MONTANA,2021-07-01,318.07,638.0,NaN,NaN,NaN,MT
6,MTM101471,DAWSON,MONTANA,2021-07-01,1600.00,3200.0,12044.0,NaN,NaN,MT
8,MTM109323,FALLON,MONTANA,2027-07-01,160.00,240.0,NaN,NaN,Keep: 7 years remaining,MT
9,MTM109324,FALLON,MONTANA,2027-07-01,120.00,180.0,NaN,NaN,Keep: 7 years remaining,MT
10,MTM109325,FALLON,MONTANA,2027-07-01,160.00,240.0,NaN,NaN,Keep: 7 years remaining,MT
11,MTM109326,FALLON,MONTANA,2027-07-01,280.00,420.0,NaN,NaN,Keep: 7 years remaining,MT
12,MTM109327,FALLON,MONTANA,2027-07-01,40.00,60.0,NaN,NaN,Keep: 7 years remaining,MT
13,MTM109328,FALLON,MONTANA,2027-07-01,200.00,300.0,1440.0,NaN,Keep: 7 years remaining,MT
15,MTM109204,GARFIELD,MONTANA,2027-07-01,360.00,540.0,NaN,NaN,NaN,MT
16,MTM109205,GARFIELD,MONTANA,2027-07-01,240.00,360.0,NaN,NaN,NaN,MT
17,MTM109206,GARFIELD,MONTANA,2027-07-01,600.00,900.0,NaN,NaN,NaN,MT
18,MTM109207,GARFIELD,MONTANA,2027-07-01,120.00,180.0,1980.0,NaN,NaN,MT
20,MTM101475,POWDER RIVER,MONTANA,2021-07-01,960.00,1920.0,NaN,NaN,NaN,MT
21,MTM101477,POWDER RIVER,MONTANA,2021-07-01,1049.60,2100.0,NaN,NaN,NaN,MT
22,MTM109357,POWDER RIVER,MONTANA,2021-07-01,280.33,421.5,NaN,NaN,NaN,MT
23,MTM109359,POWDER RIVER,MONTANA,2021-07-01,600.00,900.0,5341.5,NaN,NaN,MT
25,MTM101455,RICHLAND,MONTANA,2021-07-01,10.32,22.0,NaN,NaN,NaN,MT
26,MTM101456,RICHLAND,MONTANA,2021-07-01,5.88,12.0,NaN,NaN,NaN,MT
27,MTM101458,RICHLAND,MONTANA,2021-07-01,40.00,80.0,NaN,NaN,NaN,MT
28,MTM101466,RICHLAND,MONTANA,2021-07-01,245.38,492.0,606.0,NaN,NaN,MT
29,NaN,NaN,nan,NaT,NaN,21411.5,21411.5,NaN,NaN,NaN

In [28]:
RentalList["DI Counties"] = RentalList["COUNTY"] + " (" + RentalList["St. Initials"] + ")"

In [29]:
RentalList

,LEASE NO.,COUNTY,STATE,EXPIRATION,ACRES,RENTAL,COUNTY.1,Y/N,Mishaun Comments,St. Initials,DI Counties
0,MTM101460,DAWSON,MONTANA,2021-07-01,1193.80,2388.0,NaN,NaN,NaN,MT,DAWSON (MT)
1,MTM101461,DAWSON,MONTANA,2021-07-01,920.00,1840.0,NaN,NaN,NaN,MT,DAWSON (MT)
2,MTM101462,DAWSON,MONTANA,2021-07-01,864.95,1730.0,NaN,NaN,NaN,MT,DAWSON (MT)
3,MTM101463,DAWSON,MONTANA,2021-07-01,803.90,1608.0,NaN,NaN,NaN,MT,DAWSON (MT)
4,MTM101464,DAWSON,MONTANA,2021-07-01,320.00,640.0,NaN,NaN,NaN,MT,DAWSON (MT)
5,MTM101465,DAWSON,MONTANA,2021-07-01,318.07,638.0,NaN,NaN,NaN,MT,DAWSON (MT)
6,MTM101471,DAWSON,MONTANA,2021-07-01,1600.00,3200.0,12044.0,NaN,NaN,MT,DAWSON (MT)
8,MTM109323,FALLON,MONTANA,2027-07-01,160.00,240.0,NaN,NaN,Keep: 7 years remaining,MT,FALLON (MT)
9,MTM109324,FALLON,MONTANA,2027-07-01,120.00,180.0,NaN,NaN,Keep: 7 years remaining,MT,FALLON (MT)
10,MTM109325,FALLON,MONTANA,2027-07-01,160.00,240.0,NaN,NaN,Keep: 7 years remaining,MT,FALLON (MT)
11,MTM109326,FALLON,MONTANA,2027-07-01,280.00,420.0,NaN,NaN,Keep: 7 years remaining,MT,FALLON (MT)
12,MTM109327,FALLON,MONTANA,2027-07-01,40.00,60.0,NaN,NaN,Keep: 7 years remaining,MT,FALLON (MT)
13,MTM109328,FALLON,MONTANA,2027-07-01,200.00,300.0,1440.0,NaN,Keep: 7 years remaining,MT,FALLON (MT)
15,MTM109204,GARFIELD,MONTANA,2027-07-01,360.00,540.0,NaN,NaN,NaN,MT,GARFIELD (MT)
16,MTM109205,GARFIELD,MONTANA,2027-07-01,240.00,360.0,NaN,NaN,NaN,MT,GARFIELD (MT)
17,MTM109206,GARFIELD,MONTANA,2027-07-01,600.00,900.0,NaN,NaN,NaN,MT,GARFIELD (MT)
18,MTM109207,GARFIELD,MONTANA,2027-07-01,120.00,180.0,1980.0,NaN,NaN,MT,GARFIELD (MT)
20,MTM101475,POWDER RIVER,MONTANA,2021-07-01,960.00,1920.0,NaN,NaN,NaN,MT,POWDER RIVER (MT)
21,MTM101477,POWDER RIVER,MONTANA,2021-07-01,1049.60,2100.0,NaN,NaN,NaN,MT,POWDER RIVER (MT)
22,MTM109357,POWDER RIVER,MONTANA,2021-07-01,280.33,421.5,NaN,NaN,NaN,MT,POWDER RIVER (MT)
23,MTM109359,POWDER RIVER,MONTANA,2021-07-01,600.00,900.0,5341.5,NaN,NaN,MT,POWDER RIVER (MT)
25,MTM101455,RICHLAND,MONTANA,2021-07-01,10.32,22.0,NaN,NaN,NaN,MT,RICHLAND (MT)
26,MTM101456,RICHLAND,MONTANA,2021-07-01,5.88,12.0,NaN,NaN,NaN,MT,RICHLAND (MT)
27,MTM101458,RICHLAND,MONTANA,2021-07-01,40.00,80.0,NaN,NaN,NaN,MT,RICHLAND (MT)
28,MTM101466,RICHLAND,MONTANA,2021-07-01,245.38,492.0,606.0,NaN,NaN,MT,RICHLAND (MT)
29,NaN,NaN,nan,NaT,NaN,21411.5,21411.5,NaN,NaN,NaN,NaN

In [30]:
for i in RentalList["DI Counties"].drop_duplicates():
    print(i)

DAWSON (MT)
FALLON (MT)
GARFIELD (MT)
POWDER RIVER (MT)
RICHLAND (MT)
nan

In [31]:
RentalShapeFile

,OBJECTID_1,OBJECTID_2,OBJECTID,LEASE_NO,EFFECTIVE,EXPIRATION,TOTAL_PAID,ACRES,COUNTY,ST,...,GeneralLoc,Due_Year,DUE_DATE,NO__OF_ACR,HYPERLINK,Comments,Shape_Le_1,Shape_Le_2,Shape_Area,geometry
9,10,10,10,MTM101455,2011-07-01,2021-07-01,3021.5,10.32,RICHLAND,MT,...,None,2021,2021-07-01,10.32,None,None,3853.718897,3853.718897,3.526854e+05,MULTIPOLYGON Z (((-11709062.157 6118921.792 0....
10,11,11,11,MTM101456,2011-07-01,2021-07-01,2014.0,5.88,RICHLAND,MT,...,None,2021,2021-07-01,5.88,None,None,1781.457067,1781.457067,1.260800e+05,"POLYGON Z ((-11686184.000 6120992.000 0.000, -..."
11,12,12,12,MTM101458,2011-07-01,2021-07-01,31205.0,40.00,RICHLAND,MT,...,None,2021,2021-07-01,40.00,None,None,2418.000000,2418.000000,3.654140e+05,"POLYGON Z ((-11656641.000 6124666.000 0.000, -..."
12,13,13,13,MTM101464,2011-07-01,2021-07-01,67825.0,320.00,DAWSON,MT,...,None,2021,2021-07-01,320.00,None,None,7128.000000,7128.000000,2.813120e+06,"POLYGON Z ((-11645706.000 6037283.000 0.000, -..."
13,14,14,14,MTM101465,2011-07-01,2021-07-01,48473.5,318.07,DAWSON,MT,...,None,2021,2021-07-01,318.07,None,None,7130.447346,7130.447346,2.838999e+06,"POLYGON Z ((-11655246.000 6037269.000 0.000, -..."
14,15,15,15,MTM101475,2011-07-01,2021-07-01,73585.0,960.00,POWDER RIVER,MT,...,None,2021,2021-07-01,960.00,None,None,14866.716173,14866.716173,7.830550e+06,"POLYGON Z ((-11720137.787 5665036.311 0.000, -..."
15,16,16,16,MTM101477,2011-07-01,2021-07-01,127720.0,1049.60,POWDER RIVER,MT,...,None,2021,2021-07-01,1049.60,None,None,14869.828642,14869.828642,8.559216e+06,"POLYGON Z ((-11717846.622 5667939.790 0.000, -..."
60,61,61,61,MTM101466,2011-07-01,2021-07-01,221914.0,245.38,RICHLAND,MT,...,None,2021,2021-07-01,245.38,None,None,10905.156784,10905.156784,2.203217e+06,MULTIPOLYGON Z (((-11647796.002 6113795.567 0....
61,62,62,62,MTM101460,2011-07-01,2021-07-01,67606.0,1193.80,DAWSON,MT,...,None,2021,2021-07-01,1193.80,None,None,26906.570660,26906.570660,1.043227e+07,MULTIPOLYGON Z (((-11653818.460 5952531.989 0....
62,63,63,63,MTM101461,2011-07-01,2021-07-01,56725.0,920.00,DAWSON,MT,...,None,2021,2021-07-01,920.00,None,None,18961.005387,18961.005387,8.100227e+06,MULTIPOLYGON Z (((-11653819.350 5947782.750 0....
63,64,64,64,MTM101463,2011-07-01,2021-07-01,55621.0,803.90,DAWSON,MT,...,None,2021,2021-07-01,803.90,None,None,16521.013219,16521.013219,6.981637e+06,"POLYGON Z ((-11656196.783 5947803.691 0.000, -..."
64,65,65,65,MTM101462,2011-07-01,2021-07-01,51180.0,864.95,DAWSON,MT,...,None,2021,2021-07-01,864.95,None,None,18492.867663,18492.867663,7.546560e+06,MULTIPOLYGON Z (((-11666869.000 5946652.000 0....
65,66,66,66,MTM101471,2011-07-01,2021-07-01,130545.0,1600.00,DAWSON,MT,...,None,2021,2021-07-01,1600.00,None,None,31814.629607,31814.629607,1.400086e+07,MULTIPOLYGON Z (((-11646793.000 5945320.000 0....
108,109,109,109,MTM109204,2017-07-01,2027-07-01,0.0,360.00,GARFIELD,MT,...,Yes,2027,2027-07-01,360.00,None,None,9438.470261,9438.470261,3.135181e+06,"POLYGON Z ((-12010488.623 5950019.164 0.000, -..."
109,110,110,110,MTM109205,2017-07-01,2027-07-01,0.0,240.00,GARFIELD,MT,...,None,2027,2027-07-01,240.00,None,None,7082.599869,7082.599869,2.092680e+06,"POLYGON Z ((-12009309.176 5950019.395 0.000, -..."
110,111,111,111,MTM109206,2017-07-01,2027-07-01,0.0,600.00,GARFIELD,MT,...,None,2027,2027-07-01,600.00,None,None,9443.279797,9443.279797,5.225062e+06,"POLYGON Z ((-12009893.856 5946471.086 0.000, -..."
111,112,112,112,MTM109207,2017-07-01,2027-07-01,0.0,120.00,GARFIELD,MT,...,None,2027,2027-07-01,120.00,None,None,4722.773553,4722.773553,1.045515e+06,"POLYGON Z ((-12010486.126 5948244.533 0.000, -..."
112,113,113,113,MTM109323,2017-07-01,2027-07-01,0.0,160.00,FALLON,MT,...,None,2027,2027-07-01,160.00,None,None,4696.632613,4696.632613,1.378630e+06,"POLYGON Z ((-11605590.331 5866145.883 0.000, -..."
113,114,114,114,MTM109324,2017-07-01,2027-07-01,0.0,120.00,FALLON,MT,...,None,2027,2027-07-01,120.00,None,None,4699.322978,4699.322978,1.035152e+06,"POLYGON Z ((-11609111.634 5863786.616 0.000, -..."
114,115,115,115,MTM109325,2017-07-01,2027-07-01,0.0,160.00,FALLON,MT,...,None,2027,2027-07-01,160.00,None,None,8220.169965,8220.169965,1.379806e+06,MULTIPOLYGON Z (((-11602661.853 5862623.616 0....
115,116,116,116,MTM109326,2017-07-01,2027-07-01,0.0,280.00,FALLON,MT,...,None,2027,2027-07-01,280.00,None,None,7049.789752,7049.789752,2.413717e+06,"POLYGON Z ((-11606178.415 5860849.585 0.000, -..."
116,117,117,117,MTM109327,2017-07-01,2027-07-01,0.0,40.00,FALLON,MT,...,None,2027,2027-07-01,40.00,None,None,2347.498671,2347.498671,3.444208e+05,"POLYGON Z ((-11607349.375 5860260.528 0.000, -..."
117,118,118,118,MTM109328,2017-07-01,2027-07-01,0.0,200.00,FALLON,MT,...,None,2027,2027-07-01,200.00,None,None,9412.878494,9412.878494,1.728144e+06,MULTIPOLYGON Z (((-11612047.604 5878459.866 0....
118,119,119,119,MTM109357,2017-07-01,2027-07-01,0.0,280.33,POWDER RIVER,MT,...,None,2027,2027-07-01,280.33,None,None,9131.084457,9131.084457,2.280428e+06,MULTIPOLYGON Z (((-11715537.676 5648479.944 0....
119,120,120,120,MTM109359,2017-07-01,2027-07-01,0.0,600.00,POWDER RIVER,MT,...,None,2027,2027-07-01,600.00,None,None,10261.134267,10261.134267,4.877559e+06,"POLYGON Z ((-11715533.465 5644479.037 0.000, -..."